mode: generate
units:
  time: pico
  dist: ang
dataset:
  type: lj
  batch_size: 1
  n_atoms: 2944
  discard: -1
  n_iter: 10000
  interval: 100
  log: data/lj/log.txt
  traj: data/lj/traj.pdb
  friction: 1
  dt: 0.004
dynamics:
  checkpoint_path: model.cpt

