type: lj
batch_size: 1
discard: -1
n_atoms: 300
n_iter: 10000
interval: 100
log: log.txt
traj: traj.pdb
processed_file: processed.pt
friction: 1
dt: 0.004
cutoff: 1
r_cut: 3
temp: 298.15
softening: 0.1
box: [26, 26, 26]
natom_types: 2
units:
  time: pico
  dist: ang