mode: train
units:
  time: pico
  dist: ang
dataset:
  type: md
  batch_size: 1000
  top_file: [data/acetone/raw/acetone.tpr]
  traj_file: [data/acetone/raw/acetone.trr]
  processed_file: data/acetone/processed.pt
dynamics:
  integrator: lf
  n_iter: 5
  dt: 1
  r_cut: 3
  box_pad: 1
  checkpoint_path: model.cpt
  network:
    hidden_nf: 128
training:
  num_epochs: 5000
  lr: 1e-3
  scheduler: No
  loss:
    temp: 300
    softening: 0.1
  log_interval: 1
