training:
  num_epochs: 5000
  lr: 1e-3
  log_interval: 1
network:
  hidden_nf: 128
  n_iter: 5
  r_cut: 3
  dt: 1
  node_nf: 1
loss:
  temp: 300
  softening: 0.1
dataset:
  batch_size: 1000
  traj_file: [./lj.db]
